## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: c
sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap
  - cd
  - wget ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.20.tar.gz
  - tar zxf udunits-2.2.20.tar.gz
  - cd udunits-*
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd /home/travis/build/edzer/units

install:
  - ./pkg-build.sh install_deps

script:
  - ./pkg-build.sh run_tests

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=devel
